cmake_minimum_required(VERSION 3.25)
project(DxRenderDojo LANGUAGES CXX)

file(GLOB_RECURSE SourceFiles CONFIGURE_DEPENDS Source/*.cpp)
add_executable(DxRenderDojo WIN32 ${SourceFiles})
target_include_directories(DxRenderDojo PRIVATE Source)
target_compile_features(DxRenderDojo PRIVATE cxx_std_20)
target_compile_definitions(DxRenderDojo PRIVATE UNICODE _UNICODE WIN32_LEAN_AND_MEAN)
target_link_libraries(DxRenderDojo PRIVATE d3d11 dxgi)

if(MSVC)
	target_compile_options(DxRenderDojo PRIVATE /W3 /utf-8)
	target_sources(DxRenderDojo PRIVATE DxRenderDojo.manifest)
else()
	target_compile_options(DxRenderDojo PRIVATE -Wall)
endif()

if(MINGW)
	enable_language(RC)
	target_sources(DxRenderDojo PRIVATE DxRenderDojo.rc)
	target_compile_definitions(DxRenderDojo PRIVATE _WIN32_WINNT=0x0A00 WINVER=0x0A00)
	target_link_options(DxRenderDojo PRIVATE -municode -static -static-libgcc -static-libstdc++)
endif()
